[parity]
chain = "/chain/init/genesis.json"

[account]
password = ["/chain/init/node.pwd"]

[rpc]
disable = false
interface = "0.0.0.0"
cors = ["all"]
hosts = ["all"]
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "shh", "personal", "parity_accounts", "signer", "parity_set"]

[websockets]
disable = false
port = 8546
interface = "0.0.0.0"
origins = ["all"]
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "shh", "secretstore","pubsub"]
hosts = ["all"]

[mining]
#reseal_on_txs = "none"
#force_sealing = true
reseal_on_txs = "all"
reseal_min_period = 2000
reseal_max_period = 10000
